-
 hosts : nodes
 tasks:
   - name: creating user directories
     file:
       dest: "/home/{{ item.0 }}/{{ item.1 }}"
       owner: "{{ item.0 }}"
       group: "{{ item.0 }}"
       state: directory
     with_nested:
       - [ charan, arjun ]
       - [ photos, movies, documents ]  
